services:
  api:
    container_name: scottlms-api
    image: smchenry2014/scottlms-api:latest
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/scottlms?authSource=admin
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ../scripts:/app/scripts
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - scottlms-network

  mongodb:
    container_name: scottlms-mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=scottlms
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init-local.js:/docker-entrypoint-initdb.d/mongo-init-local.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - scottlms-network

  mongo-express:
    container_name: scottlms-mongodb-express
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8081', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - scottlms-network

  ui:
    container_name: scottlms-ui
    image: smchenry2014/scottlms-ui:latest
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8501')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - scottlms-network

volumes:
  mongodb_data:

networks:
  scottlms-network:
    driver: bridge
