# ScottLMS Application Layer
# Backend Services (API + LoadBalancer)
# This file contains the API backend and its networking

---
# API Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scottlms-api
  namespace: scottlms
  labels:
    app: scottlms-api
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: scottlms-api
  template:
    metadata:
      labels:
        app: scottlms-api
    spec:
      imagePullSecrets:
        - name: docker-hub-credentials
      containers:
        - name: scottlms-api
          image: smchenry2014/scottlms-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: scottlms-secrets
                  key: MONGODB_URL
          envFrom:
            - configMapRef:
                name: scottlms-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

---
# API Service - External LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: scottlms-api-loadbalancer
  namespace: scottlms
  labels:
    app: scottlms-api
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: scottlms-api
